"""
Django settings for biblioteca project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from .base import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'dbbiblioteca',  # Nombre de la base de datos
        'USER': 'postgres',       # Usuario de la base de datos
        'PASSWORD': 'Root123',    # Contraseña del usuario
        'HOST': 'localhost',      # El servidor de la base de datos
        'PORT': '5432',           # Puerto de PostgreSQL
    }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'  # Este es el valor estándar para servir archivos estáticos en desarrollo
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Asegúrate de que esté en la carpeta "static" en tu base de proyecto
]

# Configuración de archivos media (imágenes, archivos subidos)
MEDIA_URL = "/media/"
MEDIA_ROOT = 'C:/Users/OMAR TORRES/DESKTOP/img/'  # Esta es la carpeta donde se guardarán las imágenes

# Otros ajustes específicos para el entorno de desarrollo pueden ir aquí.

# Se desactivan para evitar que almacene en la carpeta portadas en la misma aplicación
#MEDIA_URL = "/media/"
#MEDIA_ROOT = BASE_DIR / "portadas"